import {Spot} from "../../../mongo/spots/spots";

export const newSpot=new Spot({
    userId:"test",
    spotName:"Test",
    country:"Test",
    type:[
        {
            waveType:"Test",
            bottomType:"Test",
        }
    ],
    location:{
        type:"Point",
        coordinates:["12","56"]
    },
    orientation:["Test"],
    optimalConditions:[
        {
            wind:{
                strength:"Test",
                orientation:"Test"
            },
            swell:{
                size:"Tets",
                period:"Tets",
                orientation:"Tets"
            }
        }
    ],
    sessions:["Test","Test2"],
    creationDate:Date.now(),
});

export const emptyLocation=new Spot({
    userId:"test",
    spotName:"Test",
    country:"Test",
    type:[
        {
            waveType:"Test",
            bottomType:"Test",
        }
    ],
    /*location:{
        type:"Point",
        coordinates:["12","56"]
    },*/
    orientation:["Test"],
    optimalConditions:[
        {
            wind:{
                strength:"Test",
                orientation:"Test"
            },
            swell:{
                size:"Tets",
                period:"Tets",
                orientation:"Tets"
            }
        }
    ],
    sessions:["Test","Test2"],
    creationDate:Date.now(),
});

/*sessions:[
    {
        date:Date.now(),
        startTime:Date.now(),
        endTime:Date.now(),
        totalTime:Date.now(),
        swell:{
            size:"Tets",
            period:"Tets",
            orientation:"Tets"
        },
        wind:{
            strength:"Test",
            orientation:"Test"
        },
        comment:"Test"
    }
],*/
